name: Main

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  tick:
    steps:
      - uses: actions/checkout@v2
      - name: tick
        run: |
          echo "the time is $(date)" > README.md
          git add README.md
          git commit -m "update time"
          git push origin master